### PR TITLE
Specify queue sizes for introspection publishers

### PR DESCRIPTION
**Pull request by contradict**
Unspecified queue size is deprecated under indigo.

### CODE REVIEW

**Comment by 130s** [comment]
Close-reopening to hook this PR with CI.

**Comment by 130s** [comment]
@contradict it's been awhile, but if you could rebase to the latest that'd be great (because most importantly to include `.travis.yml` for CI testing). If you can't I'll re-open this by myself.

**Comment by contradict** [comment]
Looks like this commit was already merged to master by the time I saw this message. OK with me to close assuming there are no problems. Thanks!

**Comment by 130s** [comment]
Ok I see that https://github.com/ros/executive_smach/commit/a036816bba067a18c71713009703e21e4bb9f392. And I'm now cherry-picking into indigo-devel in #48. Thanks for clarification.

**Pull request closed without merging**
