### PR TITLE
fixed ctrl+C on a concurrence container

### PR DESCRIPTION
**Pull request by athackst**
This change is [Reviewable](https://reviewable.io/reviews/ros/executive_smach/35)

### CODE REVIEW

**Comment by jbohren** [comment]
As this PR stands, it has one new busy loop that will easily soak up 100% cpu while the concurrence is executing, and another one that will do the same while it's waiting for the others to terminate. I agree that the issue is with [this line](https://github.com/ros/executive_smach/blob/indigo-devel/smach/src/smach/concurrence.py#L236) but there's nothing significant about replacing the `Condition` with an `Event`. You could also just replicate something like [this loop](https://github.com/ros/executive_smach/blob/indigo-devel/smach/src/smach/concurrence.py#L246-251) on that line, but that would also be sub-optimal

The right way to fix this is to have every `Concurrence` register its `_done_cond` or `_done_event` with whatever function is handling the `SIGINT`. That way there aren't even idle loops. Alternatively, you can make sure each state is keeping track of the global `smach.is_shutdown()` and break if that gets set.

**Comment by athackst** [comment]
So what function is handling the SIGINT for a concurrence?

**Comment by jbohren** [comment]
In `rospy`, a `SIGINT` handler gets registered. What `smach` should do is provide a global function like `smach.register_shutdown_handler()`, which would add a given callback to a list of handlers. It shold also provide a global function like `smach.handle_shutdown()` which would call all of the registered handlers. Then, what `smach_ros` should do on initialization is call `rospy.on_shutdown(smach.handle_shutdown)`.

**Comment by jbohren** [comment]
For non-ros use, you can register your own `SIGINT` handler and set it to call `smach.handle_shutdown()`.

**Comment by jbohren** [comment]
(: This would be a nice improvement and could get rid of any other loops that exist simply to check `smach.is_shutdown()`

**Comment by athackst** [comment]
I agree that sounds better.  However I can't seem to get it to work leaving in the [that line](https://github.com/ros/executive_smach/blob/indigo-devel/smach/src/smach/concurrence.py#L236).  It seems like it's blocking the main thread?  Nor does simply checking for smach.is_shutdown() in the state seem to break execution.

**Comment by athackst** [comment]
It  was blocking the main thread, which ros uses to update signals like sigint and callbacks.  I added a starting function which will spin up a state in another thread and handlers for shutdown.  To start so it doesn't block you can just do smach_ros.start(sm), where sm is the state you want tot start.

**Comment by athackst** [comment]
I also removed the smach.is_shutdown loop in concurrency since it didn't seem necessary any more.  All states should now be preempting themselves by default on shutdown and therefore terminate, but I can add it back in if you think it breaks old code.

**Comment by athackst** [comment]
We decided not to go with smach for our use case, so I'm closing this.

**Comment by jbohren** [comment]
I'd still like to merge this in with some testing on my end. So I'm going to leave it open, feel free to unsubscribe if you want, though.

**Comment by 130s** [comment]
Closing in favor of https://github.com/ros/executive_smach/pull/49

**Pull request closed without merging**
